// Available user roles in the system
export const Roles = {
    ADMIN: 'ADMIN',
    DEVELOPER: 'DEVELOPER',
    MODERATOR: 'MODERATOR',
    SUPPORT_AGENT: 'SUPPORT_AGENT',
    USER: 'USER'
}

// Available permissions in the system
export const Permissions = {
    // Ticket System
    CREATE_TICKET: 'CREATE_TICKET',
    VIEW_TICKET: 'VIEW_TICKET',
    CLOSE_TICKET: 'CLOSE_TICKET',
    ASSIGN_TICKET: 'ASSIGN_TICKET',
    MANAGE_TICKETS: 'MANAGE_TICKETS',
    ESCALATE_TICKET: 'ESCALATE_TICKET',
    VIEW_ALL_TICKETS: 'VIEW_ALL_TICKETS',

    // User Management
    BAN_USER: 'BAN_USER',
    UNBAN_USER: 'UNBAN_USER',
    WARN_USER: 'WARN_USER',
    MANAGE_ROLES: 'MANAGE_ROLES',
    VIEW_USER_INFO: 'VIEW_USER_INFO',
    MANAGE_USER_PROFILE: 'MANAGE_USER_PROFILE',

    // Knowledge Base
    VIEW_KB: 'VIEW_KB',
    CREATE_KB: 'CREATE_KB',
    EDIT_KB: 'EDIT_KB',
    DELETE_KB: 'DELETE_KB',
    VERIFY_KB: 'VERIFY_KB',

    // System Commands
    VIEW_SYSTEM_STATUS: 'VIEW_SYSTEM_STATUS',
    VIEW_METRICS: 'VIEW_METRICS',
    MANAGE_BOT_SETTINGS: 'MANAGE_BOT_SETTINGS',

    // Support System
    PROVIDE_SUPPORT: 'PROVIDE_SUPPORT',
    VIEW_SUPPORT_QUEUE: 'VIEW_SUPPORT_QUEUE',
    MANAGE_SUPPORT_AGENTS: 'MANAGE_SUPPORT_AGENTS',

    // Moderation
    DELETE_MESSAGES: 'DELETE_MESSAGES',
    TIMEOUT_USER: 'TIMEOUT_USER',
    VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
    MANAGE_THREADS: 'MANAGE_THREADS',

    // Server Management
    MANAGE_PTERODACTYL: 'MANAGE_PTERODACTYL',
    VIEW_SERVER_STATUS: 'VIEW_SERVER_STATUS',
    RESTART_SERVERS: 'RESTART_SERVERS',
    MODIFY_SERVER_CONFIG: 'MODIFY_SERVER_CONFIG'
}
